# Generated by go2rpm 1.3
%if 0%{?fedora}
%bcond_without check
%else
# %%gocheck isn't currently provided on CentOS/RHEL
# https://bugzilla.redhat.com/show_bug.cgi?id=1982298
%bcond_with check
%endif

%global debug_package   %{nil}
%global _find_debuginfo_dwz_opts %{nil}
%global _buildhost build-ol%{?oraclelinux}-%{?_arch}.oracle.com

%define mapped_arch %( \
      arch=$(uname -m); \
      if [ "$arch" = "x86_64" ]; then \
          echo "amd64"; \
      elif [ "$arch" = "aarch64" ]; then \
          echo "arm64"; \
      else \
          echo "$arch"; \
      fi \
  )

%global ignedgecommit 35853ded31252937d3390970a89885478651c12e
%global ignedgeshortcommit %(c=%{ignedgecommit}; echo ${c:0:7})

# https://github.com/coreos/ignition
Version:                2.16.2

%global dracutlibdir %{_prefix}/lib/dracut

Name:           ignition
Release:        5%{?dist}
Summary:        First boot installer and configuration tool (RHEL CoreOS only)

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{name}-%{version}.tar.bz2
Source1:        ignition-edge-%{ignedgeshortcommit}.tar.gz
Patch0:         add-oci-provider.patch
Patch1:         oci-provider.patch
Patch2:         disable-preset.patch

BuildRequires: libblkid-devel
BuildRequires: systemd-rpm-macros

# Requires for 'disks' stage
%if 0%{?fedora}
Recommends: btrfs-progs
%endif
Requires: dosfstools
Requires: gdisk
Requires: dracut
Requires: dracut-network

Obsoletes: ignition-dracut < 0.31.0-3

# Generated by `go-mods-to-bundled-provides.py | sort`
Provides: bundled(golang(cloud.google.com/go/compute/metadata)) = 0.2.3
Provides: bundled(golang(cloud.google.com/go/storage)) = 1.31.0
Provides: bundled(golang(cloud.google.com/go/storage/internal)) = 1.31.0
Provides: bundled(golang(cloud.google.com/go/storage/internal/apiv2)) = 1.31.0
Provides: bundled(golang(cloud.google.com/go/storage/internal/apiv2/storagepb)) = 1.31.0
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/arn)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/auth/bearer)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/awserr)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/awsutil)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/client)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/client/metadata)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/corehandlers)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/credentials)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/credentials/endpointcreds)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/credentials/processcreds)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/credentials/ssocreds)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/credentials/stscreds)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/csm)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/defaults)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/ec2metadata)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/endpoints)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/request)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/session)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/aws/signer/v4)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/context)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/ini)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/s3shared)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/s3shared/arn)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/s3shared/s3err)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/sdkio)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/sdkmath)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/sdkrand)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/sdkuri)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/shareddefaults)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/strings)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/internal/sync/singleflight)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/checksum)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/eventstream)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/json/jsonutil)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/jsonrpc)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/query)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/query/queryutil)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/rest)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/restjson)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/restxml)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/service/s3)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/service/s3/s3iface)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/service/s3/s3manager)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/service/sso)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/service/sso/ssoiface)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/service/ssooidc)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/service/sts)) = 1.44.298
Provides: bundled(golang(github.com/aws/aws-sdk-go/service/sts/stsiface)) = 1.44.298
Provides: bundled(golang(github.com/beevik/etree)) = 1.2.0
Provides: bundled(golang(github.com/containers/libhvee/pkg/kvp)) = 0.3.0
Provides: bundled(golang(github.com/coreos/go-semver/semver)) = 0.3.1
Provides: bundled(golang(github.com/coreos/go-systemd/v22/dbus)) = 22.5.0
Provides: bundled(golang(github.com/coreos/go-systemd/v22/journal)) = 22.5.0
Provides: bundled(golang(github.com/coreos/go-systemd/v22/unit)) = 22.5.0
Provides: bundled(golang(github.com/coreos/vcontext/json)) = 0.0.0-20230201181013.gitd72178a18687
Provides: bundled(golang(github.com/coreos/vcontext/path)) = 0.0.0-20230201181013.gitd72178a18687
Provides: bundled(golang(github.com/coreos/vcontext/report)) = 0.0.0-20230201181013.gitd72178a18687
Provides: bundled(golang(github.com/coreos/vcontext/tree)) = 0.0.0-20230201181013.gitd72178a18687
Provides: bundled(golang(github.com/coreos/vcontext/validate)) = 0.0.0-20230201181013.gitd72178a18687
Provides: bundled(golang(github.com/google/renameio/v2)) = 2.0.0
Provides: bundled(golang(github.com/google/uuid)) = 1.3.0
Provides: bundled(golang(github.com/mitchellh/copystructure)) = 1.2.0
Provides: bundled(golang(github.com/pin/tftp)) = 2.1.0
Provides: bundled(golang(github.com/pin/tftp/netascii)) = 2.1.0
Provides: bundled(golang(github.com/spf13/pflag)) = 1.0.6-0.20210604193023.gitd5e0c0615ace
Provides: bundled(golang(github.com/stretchr/testify/assert)) = 1.8.4
Provides: bundled(golang(github.com/vincent-petithory/dataurl)) = 1.0.0
Provides: bundled(golang(github.com/vmware/vmw-guestinfo/bdoor)) = 0.0.0-20220317130741.git510905f0efa3
Provides: bundled(golang(github.com/vmware/vmw-guestinfo/message)) = 0.0.0-20220317130741.git510905f0efa3
Provides: bundled(golang(github.com/vmware/vmw-guestinfo/rpcout)) = 0.0.0-20220317130741.git510905f0efa3
Provides: bundled(golang(github.com/vmware/vmw-guestinfo/rpcvmx)) = 0.0.0-20220317130741.git510905f0efa3
Provides: bundled(golang(github.com/vmware/vmw-guestinfo/vmcheck)) = 0.0.0-20220317130741.git510905f0efa3
Provides: bundled(golang(golang.org/x/net/context)) = 0.12.0
Provides: bundled(golang(golang.org/x/net/http/httpguts)) = 0.12.0
Provides: bundled(golang(golang.org/x/net/http/httpproxy)) = 0.12.0
Provides: bundled(golang(golang.org/x/net/http2)) = 0.12.0
Provides: bundled(golang(golang.org/x/net/http2/hpack)) = 0.12.0
Provides: bundled(golang(golang.org/x/net/idna)) = 0.12.0
Provides: bundled(golang(golang.org/x/net/internal/timeseries)) = 0.12.0
Provides: bundled(golang(golang.org/x/net/trace)) = 0.12.0
Provides: bundled(golang(golang.org/x/oauth2)) = 0.10.0
Provides: bundled(golang(golang.org/x/oauth2/authhandler)) = 0.10.0
Provides: bundled(golang(golang.org/x/oauth2/google)) = 0.10.0
Provides: bundled(golang(golang.org/x/oauth2/google/internal/externalaccount)) = 0.10.0
Provides: bundled(golang(golang.org/x/oauth2/internal)) = 0.10.0
Provides: bundled(golang(golang.org/x/oauth2/jws)) = 0.10.0
Provides: bundled(golang(golang.org/x/oauth2/jwt)) = 0.10.0
Provides: bundled(golang(golang.org/x/sys/cpu)) = 0.10.0
Provides: bundled(golang(golang.org/x/sys/unix)) = 0.10.0
Provides: bundled(golang(google.golang.org/api/googleapi)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/googleapi/transport)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/iamcredentials/v1)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/internal)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/internal/cert)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/internal/gensupport)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/internal/impersonate)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/internal/third_party/uritemplates)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/iterator)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/option)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/option/internaloption)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/storage/v1)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/transport)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/transport/grpc)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/transport/http)) = 0.130.0
Provides: bundled(golang(google.golang.org/api/transport/http/internal/propagation)) = 0.130.0
Provides: bundled(golang(gopkg.in/yaml.v3)) = 3.0.1

%description
This software is currently only supported on RHEL CoreOS.

Ignition is a utility used to manipulate systems during the initramfs.
This includes partitioning disks, formatting partitions, writing files
(regular files, systemd units, etc.), and configuring users. On first
boot, Ignition reads its configuration from a source of truth (remote
URL, network metadata service, hypervisor bridge, etc.) and applies
the configuration.

############## validate subpackage ##############

%package validate

Summary:  Validation tool for Ignition configs
License:  ASL 2.0

Conflicts: ignition < 0.31.0-3

%description validate
Ignition is a utility used to manipulate systems during the initramfs.
This includes partitioning disks, formatting partitions, writing files
(regular files, systemd units, etc.), and configuring users. On first
boot, Ignition reads its configuration from a source of truth (remote
URL, network metadata service, hypervisor bridge, etc.) and applies
the configuration.

This package contains a tool for validating Ignition configurations.

############## ignition-edge subpackage ##############

%if 0%{?rhel} && !0%{?eln}
%package edge

Summary:  Enablement glue for Ignition on IoT/Edge systems
License:  ASL 2.0

%description edge
This package contains dracut modules, services and binaries needed to enable
Ignition on IoT/Edge systems.
%endif

%prep
%if 0%{?fedora}
%autopatch -p2
%else
%forgeautosetup -p2
tar xvf %{SOURCE1}
%endif

%build
GLDFLAGS="-X github.com/coreos/ignition/v2/internal/distro.selinuxRelabel=true " ./build

%install
# dracut modules
install -d -p %{buildroot}/%{dracutlibdir}/modules.d
cp -r dracut/* %{buildroot}/%{dracutlibdir}/modules.d/
install -m 0644 -D -t %{buildroot}/%{_unitdir} systemd/ignition-delete-config.service
install -m 0755 -d %{buildroot}/%{_libexecdir}
ln -sf ../lib/dracut/modules.d/30ignition/ignition %{buildroot}/%{_libexecdir}/ignition-apply
ln -sf ../lib/dracut/modules.d/30ignition/ignition %{buildroot}/%{_libexecdir}/ignition-rmcfg

# ignition
install -d -p %{buildroot}%{_bindir}
install -p -m 0755 ./bin/%{mapped_arch}/ignition-validate %{buildroot}%{_bindir}

# The ignition binary is only for dracut, and is dangerous to run from
# the command line.  Install directly into the dracut module dir.
install -p -m 0755 ./bin/%{mapped_arch}/ignition %{buildroot}/%{dracutlibdir}/modules.d/30ignition

%if 0%{?rhel} && !0%{?eln}
%make_install -C ignition-edge-%{ignedgecommit}
%endif

%if %{with check}
%check
# Exclude the blackbox tests
%gocheck -t tests
%endif

%files
%license LICENSE olm/SECURITY.md THIRD_PARTY_LICENSES.txt
%doc README.md docs/
%{dracutlibdir}/modules.d/30ignition/*
%{_unitdir}/ignition-delete-config.service
%{_libexecdir}/ignition-apply
%{_libexecdir}/ignition-rmcfg

%files validate
%doc README.md
%license LICENSE
%{_bindir}/ignition-validate

%if 0%{?rhel} && !0%{?eln}
%files edge
%license LICENSE
%doc README.md docs/
%{dracutlibdir}/modules.d/35ignition-edge/*
%{dracutlibdir}/modules.d/10coreos-sysctl/*
%{dracutlibdir}/modules.d/99emergency-shell-setup/*
%{dracutlibdir}/modules.d/99journal-conf/*
%{_unitdir}/coreos-check-ssh-keys.service
%{_unitdir}/coreos-ignition-write-issues.service
%{_unitdir}/ignition-firstboot-complete.service
%{_libexecdir}/coreos-ignition-write-issues
%{_libexecdir}/coreos-check-ssh-keys
%endif

%changelog
* Tue Nov 25 2025 Daniel Krasinski <daniel.krasinski@oracle.com> - 2.16.2-5
- Fix CVE-2025-22869 and CVE-2025-22868

* Wed Feb 19 2025 Daniel Krasinski <daniel.krasinski@oracle.com> - 2.16.2-4
- Fix CVEs

* Fri Dec 20 2024 Daniel Krasinski <daniel.krasinski@oracle.com> - 2.16.2-3
- Unconditionally add disabled units to preset files

* Fri May 03 2024 Fred Tibbitts <fred.tibbitts@oracle.com> - 2.16.2-2
- Add OCI provider
- Add third party license file

* Thu Jul 13 2023 Benjamin Gilbert <bgilbert@redhat.com> - 2.16.2-1
- New release

* Tue May 30 2023 Antonio Murdaca <antoniomurdaca@gmail.com> - 2.15.0-2
- Fix Edge's Anaconda installer (#2203233)

* Wed Feb 22 2023 Benjamin Gilbert <bgilbert@redhat.com> - 2.15.0-1
- New release
- Clarify -edge subpackage summary and description

* Tue Nov 22 2022 Antonio Murdaca <antoniomurdaca@gmail.com> - 2.14.0-4
- Rebuild to include ignition-edge subpackage (#2144789)

* Mon Oct 10 2022 Benjamin Gilbert <bgilbert@redhat.com> - 2.14.0-3
- Rebuild for unblocking ignition-validate subpackage (#2121002)

* Tue Aug 9 2022 Christian Glombek <cglombek@redhat.com> - 2.14.0-2
- Enable writing ssh keys fragments on RHEL/CentOS >= 9

* Thu May 26 2022 Benjamin Gilbert <bgilbert@redhat.com> - 2.14.0-1
- New release
- Add ignition-apply symlink
- Add ignition-rmcfg symlink and ignition-delete-config.service

* Mon Mar 21 2022 Sohan Kunkerkar <skunkerk@redhat.com> - 2.13.0-2
- Rename -validate-nonlinux subpackage to -validate-redistributable
- Add static Linux binaries to -redistributable
- Fix macro invocation in comment
- Avoid kernel lockdown on VMware when running with secure boot

* Thu Jan 20 2022 Benjamin Gilbert <bgilbert@redhat.com> - 2.13.0-1
- New release
- Fix LUKS volume reuse
- Avoid double patch application

* Thu Sep 16 2021 Sohan Kunkerkar <skunkerk@redhat.com> - 2.12.0-1
- Suppress hardcoded library path warning
- Fix go-mods-to-bundled-provides script to parse correct rpm version
- Import specfile from Fedora

* Mon Aug 09 2021 Mohan Boddu <mboddu@redhat.com> - 2.9.0-7
- Rebuilt for IMA sigs, glibc 2.34, aarch64 flags
  Related: rhbz#1991688

* Tue Jun 22 2021 Mohan Boddu <mboddu@redhat.com> - 2.9.0-6
- Rebuilt for RHEL 9 BETA for openssl 3.0
  Related: rhbz#1971065

* Fri Apr 16 2021 Mohan Boddu <mboddu@redhat.com> - 2.9.0-5
- Rebuilt for RHEL 9 BETA on Apr 15th 2021. Related: rhbz#1947937

* Fri Feb 05 2021 Benjamin Gilbert <bgilbert@redhat.com> - 2.9.0-4
- Drop Git commit hash from Release
- Correctly enable IMDS patch
- Switch to %%autosetup
- Set ExclusiveArch from %%go_arches
- Drop mention of networkd in package description

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 2.9.0-3.git1d56dc8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Jan 12 2021 Sohan Kunkerkar <skunkerk@redhat.com> - 2.9.0-2.git1d56dc8
- Fix AWS probing by using the IMDS token URL to ensure that networking is up

* Fri Jan 08 2021 Sohan Kunkerkar <skunkerk@redhat.com> - 2.9.0-1.git1d56dc8
- New release

* Thu Dec 03 2020 Sohan Kunkerkar <skunkerk@redhat.com> - 2.8.1-1.gitc733d23
- New release

* Wed Nov 25 2020 Sohan Kunkerkar <skunkerk@redhat.com> - 2.8.0-1.gitdb4d30d
- New release

* Wed Oct 14 2020 Stephen Lowrie <slowrie@redhat.com> - 2.7.0-1.git5be43fd
- New release

* Wed Aug 12 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.6.0-2.git947598e
- Fix sector size detection on s390x

* Fri Aug 07 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.6.0-1.git947598e
- New release

* Fri Aug 07 2020 Jonathan Lebon <jonathan@jlebon.com> - 2.5.0-3.git0d6f3e5
- Backport conditional networking fix for OpenStack and CloudStack
  https://github.com/coreos/ignition/pull/1057

* Tue Jul 28 2020 Fedora Release Engineering <releng@fedoraproject.org> - 2.5.0-2.git0d6f3e5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Thu Jul 23 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.5.0-1.git0d6f3e5
- New release
- Ship support code from Ignition tarball instead of ignition-dracut

* Thu Jul 16 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.4.1-1.git5260a5b
- New release
- Bump ignition-dracut to fix warning in udev rule

* Wed Jul 15 2020 Jonathan Lebon <jonathan@jlebon.com> - 2.4.0-2.gitd18bf90
- Backport root homedir relabeling fix
  https://github.com/coreos/ignition/pull/1029 for
  https://github.com/coreos/fedora-coreos-config/pull/426#issuecomment-658867731.

* Mon Jul 13 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.4.0-1.gitd18bf90
- New release
- Bump ignition-dracut

* Mon Jun 15 2020 Timothée Ravier <travier@redhat.com> - 2.3.0-3.gitee616d5
- Update to latest ignition-dracut to fix coreos-gpt-setup unit
  https://github.com/coreos/ignition-dracut/pull/191

* Mon Jun 01 2020 Jonathan Lebon <jonathan@jlebon.com> - 2.3.0-2.gitee616d5
- Update to latest ignition-dracut to fix error handling
  https://github.com/coreos/ignition-dracut/pull/188

* Tue May 05 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.3.0-1.gitee616d5
- New release
- Bump ignition-dracut

* Sun Apr 26 2020 Dusty Mabe <dusty@dustymabe.com> - 2.2.1-5.git2d3ff58
- Update to latest ignition-dracut for network fixes
  https://github.com/coreos/ignition-dracut/pull/174

* Thu Apr 16 2020 Colin Walters <walters@verbum.org> - 2.2.1-4.git2d3ff58
- Update to latest ignition-dracut for virtio dump

* Mon Mar 30 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.2.1-3.git2d3ff58
- Bump ignition-dracut to fix umount stage network access

* Sat Mar 28 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.2.1-2.git2d3ff58
- Fix userdata/metadata fetch on Packet

* Tue Mar 24 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.2.1-1.git2d3ff58
- New release
- Bump ignition-dracut for initramfs network teardown

* Sat Feb 01 2020 Benjamin Gilbert <bgilbert@redhat.com> - 2.1.1-6.git40c0b57
- Switch -validate-nonlinux to noarch; move files to /usr/share/ignition
- Improve -validate-nonlinux descriptive text

* Fri Jan 31 2020 Jonathan Lebon <jonathan@jlebon.com> - 2.1.1-5.git40c0b57
- Bump ignition-dracut for ignition-diskful-subsequent target
  https://github.com/coreos/ignition-dracut/pull/151
- Kill grub dropin
  https://github.com/coreos/ignition-dracut/pull/91

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 2.1.1-4.git40c0b57
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Dec 20 2019 Dusty Mabe <dusty@dustymabe.com> - 2.1.1-3.git40c0b57
- Backport upstream patch to workaround problem booting on live systems
    - https://github.com/coreos/fedora-coreos-tracker/issues/339
    - https://github.com/coreos/ignition/pull/907

* Tue Dec 17 2019 Andrew Jeddeloh <ajeddelo@redhat.com> - 2.1.1-2.git40c0b57
- Add ignition-validate-nonlinux subpackage. This should not be installed. It
  is only used for building binaries to sign by Fedora release engineering and
  include on the Ignition project's Github releases page.

* Fri Dec 13 2019 Andrew Jeddeloh <ajeddelo@redhat.com> - 2.1.1-1.git40c0b57
- New release 2.1.1

* Mon Dec 09 2019 Jonathan Lebon <jonathan@jlebon.com> - 2.0.1-9.gita8f91fa
- Use the master branch of ignition-dracut, not spec2x

* Fri Dec 06 2019 Jonathan Lebon <jonathan@jlebon.com> - 2.0.1-8.gita8f91fa
- Bump Ignition for that sweet SELinux labeling:
  https://github.com/coreos/ignition/pull/846

* Thu Dec 05 2019 Jonathan Lebon <jonathan@jlebon.com> - 2.0.1-7.git641ec6a
- Don't require btrfs-progs, just recommend it
  https://github.com/coreos/fedora-coreos-tracker/issues/323

* Wed Dec 04 2019 Allen Bai <abai@redhat.com> - 2.0.1-6.git641ec6a
- Update dracut to latest spec2x
    * firstboot-complete: tell zipl to run

* Thu Oct 31 2019 Colin Walters <walters@verbum.org> - 2.0.1-5.git641ec6a
- Update dracut

* Wed Sep 25 2019 Colin Walters <walters@verbum.org> - 2.0.1-4.git641ec6a
- Bump to latest in prep for rootfs redeploy work

* Sat Sep 21 2019 Peter Robinson <pbrobinson@fedoraproject.org> 2.0.1-3.gite75cf24
- Fix up arch dependencies for new golang specs

* Fri Aug 16 2019 Colin Walters <walters@verbum.org> - 2.0.1-2.gite75cf24
- Update dracut for gpt fixes

* Thu Jul 25 2019 Andrew Jeddeloh <ajeddelo@redhat.com> - 2.0.1-1.gite75cf24
- New release 2.0.1

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 2.0.0-2.git0c1da80
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Mon Jun 10 2019 Andrew Jeddeloh <ajeddelo@redhat.com> - 2.0.0-1.git0c1da80
- New release 2.0.0

* Fri May 03 2019 Jonathan Lebon <jonathan@jlebon.com> - 2.0.0-beta.3.git910e6c6
- Adapt distro.selinuxRelabel flag path for v2/ move

* Fri May 03 2019 Jonathan Lebon <jonathan@jlebon.com> - 2.0.0-beta.2.git910e6c6
- Bump ignition-dracut dropping CoreOS integration files

* Mon Apr 29 2019 Andrew Jeddeloh <ajeddelo@redhat.com> - 2.0.0-beta.1.git910e6c6
- New release 2.0.0-beta

* Mon Apr 08 2019 Jonathan Lebon <jonathan@jlebon.com> - 2.0.0-alpha.3.git906cf04
- ignition-dracut: update to latest
    * dracut/30ignition: link to RHBZ in ignition-complete
    * dracut/30ignition: add OnFailure= for ExecStop= services
    * dracut/30ignition: order ExecStop= units before initrd-switch-root.target
    * dracut/30ignition: re-order directives in remount-sysroot
    * dracut/30ignition: add missing Before= for mount unit
    * dracut/30ignition: order ignition-complete.target before initrd.target
    * module_setup: include cdrom rules for openstack

* Wed Mar 27 2019 Benjamin Gilbert <bgilbert@backtick.net> - 2.0.0-alpha.2.git906cf04
- Backport fix for SELinux relabeling of systemd units
- Drop obsolete override of chroot path

* Wed Mar 27 2019 Jonathan Lebon <jonathan@jlebon.com> - 2.0.0-alpha.1.git906cf04
- New release 2.0.0-alpha
- ignition-dracut: Go back to master branch

* Fri Mar 22 2019 Dusty Mabe <dusty@dustymabe.com> - 0.31.0-7.gitf59a653
- ignition-dracut: Pull in latest from spec2x branch
    * grub: support overriding network kcmdline args
- ignition: pull in subuid/subgid files patch from spec2x branch
    * stages/files: Also relabel subuid/subgid files

* Wed Mar 20 2019 Michael Nguyen <mnguyen@redhat.com> - 0.31.0-6.gitf59a653
- Backport patch for supporting guestinfo.ignition.config.data

* Mon Mar 18 2019 Dusty Mabe <dusty@dustymabe.com> - 0.31.0-5.gitf59a653
- Use the spec2x branch of ignition-dracut upstream
- * Since ignition-dracut master has moved to supporting ignition
    spec 3.x we are applying 2.x related fixes to the spec2x
    branch in the ignition-dracut repo.
  * Summary of backports: https://github.com/coreos/ignition-dracut/pull/58

* Mon Mar 18 2019 Benjamin Gilbert <bgilbert@backtick.net> - 0.31.0-4.gitf59a653
- Move dracut modules into main ignition package
- Move ignition binary out of the PATH
- Move ignition-validate into a subpackage
- Include ignition-dracut license file
- Drop developer docs from base package

* Mon Mar 18 2019 Colin Walters <walters@verbum.org> - 0.31.0-3.gitf59a653
- Backport patch for networking

* Mon Mar 04 2019 Dusty Mabe <dusty@dustymabe.com> - 0.31.0-2.gitf59a653
- ignition-dracut: backport patch for finding ignition.firstboot file on UEFI systems
  https://github.com/coreos/ignition-dracut/pull/52

* Wed Feb 20 2019 Andrew Jeddeloh <andrew.jeddeloh@redhat.com> - 0.31.0-1.gitf59a653
- New release 0.31.0

* Fri Feb 15 2019 Dusty Mabe <dusty@dustymabe.com> - 0.30.0-4.git308d7a0
- Bump to ignition-dracut 2c69925
- * support platform configs and user configs in /boot
    ^ https://github.com/coreos/ignition-dracut/pull/43
  * Add ability to parse config.ign file on boot
    ^ https://github.com/coreos/ignition-dracut/pull/42

* Fri Feb 01 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.30.0-3.git308d7a0
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Mon Jan 28 2019 Dusty Mabe <dusty@dustymabe.com> - 0.30.0-2.git308d7a0
- Bump to ignition-dracut fa7131b
- * 7579b92 journal: add clarifying comment for context
  * a6551f1 Remount /sysroot rw (#38)
  * ignition-firstboot-complete.service: Remount /boot rw

* Sat Dec 15 2018 Benjamin Gilbert <bgilbert@redhat.com> - 0.30.0-1.git308d7a0
- New release 0.30.0

* Fri Dec 14 2018 Michael Nguyen <mnguyen@redhat.com> - 0.29.1-3.gitb1ab0b2
- define gopath for RHEL7

* Tue Dec 11 2018 Dusty Mabe <dusty@dustymabe.com> - 0.29.1-2.gitb1ab0b2
- require golang >= 1.10 and specify architecture list for RHEL7

* Tue Dec 11 2018 Andrew Jeddeloh <andrew.jeddeloh@redhat.com> - 0.29.1-1.gitb1ab0b2
- New release 0.29.1

* Wed Nov 21 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.28.0-12.gitf707912
- Rebuild for protobuf 3.6 in rawhide (f30)

* Tue Nov 20 2018 Jonathan Lebon <jonathan@jlebon.com> - 0.28.0-11.git7b83454
- Bump to ignition-dracut 7b83454

* Thu Oct 25 2018 Dusty Mabe <dusty@dustymabe.com> - 0.28.0-10.gitf707912
- Bump to ignition-dracut decf63f
- * 03d8438 30ignition: only instmods if module available

* Thu Oct 25 2018 Dusty Mabe <dusty@dustymabe.com> - 0.28.0-9.gitf707912
- Bump to ignition-dracut 7ee64ca
- * 3ec0b39 remove ignition-remount-sysroot.service files
  * 66335f2 ignition: run files stage at original CL ordering
  * 0301a03 ignition-disks.service: drop Requires=network.target
  * a0bc135 ignition-ask-var-mount.service: use RemainAfterExit=yes
  * ecf5779 module-setup.sh: explicitly install qemu_fw_cfg

* Mon Oct 15 2018 Dusty Mabe <dusty@dustymabe.com> - 0.28.0-8.gitf707912
- Bump to ignition-dracut 4bdfb34
- * 6d0763a module-setup: Make mkfs.btrfs optional

* Wed Oct 10 2018 Jonathan Lebon <jonathan@jlebon.com> - 0.28.0-7.gitf707912
- Backport patch for handling sysctl files correctly
  https://github.com/coreos/coreos-assembler/pull/128
  https://github.com/openshift/machine-config-operator/pull/123

* Wed Sep 26 2018 Dusty Mabe <dusty@dustymabe.com> - 0.28.0-6.gitf707912
- Bump to ignition-dracut c09ce6f
- * ce9f648 30ignition: add support for ignition-disks

* Mon Sep 24 2018 Dusty Mabe <dusty@dustymabe.com> - 0.28.0-5.gitf707912
- Remove requires for btrfs on !fedora
- Bump to ignition-dracut 8c85eb3
- * 26f2396 journal: Don't log to console AND kmsg

* Mon Sep 17 2018 Jonathan Lebon <jonathan@jlebon.com> - 0.28.0-4.gitf707912
- Backport patch for relabeling /var/home on FCOS
  https://github.com/coreos/fedora-coreos-config/issues/2

* Thu Sep 06 2018 Luca Bruno <lucab@fedoraproject.org> - 0.28.0-3.gitf707912
- Add requires for disks stage

* Thu Aug 30 2018 Dusty Mabe <dusty@dustymabe.com> - 0.28.0-2.gitf707912
- Bump to ignition-dracut d056287
- * 3f41219 dracut/ignition: remove CL-legacy udev references
- * 92ef9dd coreos-firstboot-complete: RemainAfterExit=yes

* Thu Aug 30 2018 Andrew Jeddeloh <andrewjeddeloh@redhat.com> - 0.28.0-1.gitf707912
- New release 0.28.0

* Fri Aug 17 2018 Dusty Mabe <dusty@dustymabe.com> - 0.27.0-3.gitcc7ebe0
- Bump to ignition-dracut 56aa514

* Wed Aug 15 2018 Jonathan Lebon <jonathan@jlebon.com> - 0.27.0-2.gitcc7ebe0
- Backport patch for /root relabeling
  https://github.com/coreos/ignition/pull/613

* Fri Aug 10 2018 Jonathan Lebon <jonathan@jlebon.com> - 0.27.0-1.gitcc7ebe0
- New release 0.27.0

* Sat Jul 21 2018 Dusty Mabe <dusty@dustymabe.com> - 0.26.0-0.6.git7610725
- Bump to ignition-dracut d664657

* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.26.0-0.5.git7610725
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Fri Jun 29 2018 Dusty Mabe <dusty@dustymabe.com> - 0.26.0-0.4.git7610725
- Fix building on el7 (install -D not working)

* Fri Jun 29 2018 Dusty Mabe <dusty@dustymabe.com> - 0.26.0-0.3.git7610725
- Bump to ignition-dracut 17a201b

* Tue Jun 26 2018 Dusty Mabe <dusty@dustymabe.com> - 0.26.0-0.2.git7610725
- Rename dustymabe/bootengine upstrem to dustymabe/ignition-dracut

* Thu Jun 21 2018 Dusty Mabe <dusty@dustymabe.com> - 0.26.0-0.1.git7610725
- First package for Fedora
